# This workflow publishes both crates to crates.io and creates a GitHub release when a new tag is pushed (e.g. v0.1.0)
name: Release & Publish

on:
  push:
    tags:
      - 'v*'    # Only run on version tags

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-sys:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: kinect-v2-sys
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-pc-windows-msvc
      - name: Verify kinect-v2-sys
        run: cargo publish --dry-run
      - name: Publish kinect-v2-sys to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish

  publish:
    runs-on: windows-latest
    needs: publish-sys
    defaults:
      run:
        working-directory: kinect-v2
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-pc-windows-msvc
      - name: Verify kinect-v2
        run: cargo publish --dry-run
      - name: Publish kinect-v2 to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish

  github-release:
    runs-on: windows-latest
    needs: publish
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
